[package]
name = "presspeek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
egui = "0.14"
egui_glium = "0.14"
egui_web = "0.14"
